services:
  app:
    build: .
    command: bash -c "composer install --no-interaction && sleep 3 && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
    volumes:
      - .:/app
    ports:
      - "3003:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:Qt6ivpiUIvetQAo3RbrDvAb8EadCCm8xY0Cf7XcnocU=
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: codelens
      DB_USERNAME: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      QUEUE_CONNECTION: database
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GITHUB_TOKEN: ${GITHUB_TOKEN}

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codelens
    ports:
      - "5434:5432"
    volumes:
      - codelens_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  worker:
    build: .
    command: bash -c "sleep 3 && php artisan queue:work --sleep=3 --tries=1 --timeout=360 --no-interaction"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:Qt6ivpiUIvetQAo3RbrDvAb8EadCCm8xY0Cf7XcnocU=
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: codelens
      DB_USERNAME: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      QUEUE_CONNECTION: database
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GITHUB_TOKEN: ${GITHUB_TOKEN}

  redis:
    image: redis:7
    ports:
      - "6381:6379"

volumes:
  codelens_pg:
